name: Unit Tests

on:
  push:
    branches: [main]  # Run the tests on pushes to the 'main' branch
  pull_request:
    branches: [main]  # Run the tests on pull requests targeting the 'main' branch

jobs:
  frontend_tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install Backend dependencies
        run: |
          cd backend
          pip install -r requirements.txt
      - name: Run backend
        run: |
          cd backend
          fastapi dev src/app.py
      - name: Install npm Dependencies
        run: |
          cd frontend
          npm install
      - name: Wait for Backend to be Ready
        run: |
          # Wait until the backend is fully ready (ASSUMES PORT 8000)
          while ! nc -z localhost 8000; do
            echo "Waiting for backend to be ready..."
            sleep 2
          done
      - name: Unit Test
        run: |
          cd frontend
          npm test

  backend_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install Dependencies
        run: |
          cd backend
          pip install -r requirements.txt

      - name: Run Python Tests
        run: |
          cd backend
          pytest --maxfail=0 --disable-warnings -q
